copyright: Copyright &copy; 2016 - 2030
edit_uri: edit/main/docs/
extra:
  customer:
    name: Your name here
    salt: salt.example.com
    web: www.example.com
  homepage: https://example.com
  mystatic: http://cl1157:15720/
  social:
  - icon: fontawesome/brands/gitlab
    link: http://cl1157:30010/
    name: gitlab
  tags:
    CSS: css
    HTML5: html
    JavaScript: js
    mkdocs: mkdocs
extra_css:
- stylesheets/admonitions.css
- stylesheets/extra.css
- stylesheets/Annotations.css
- stylesheets/tab.css
- components/img_click.css
extra_javascript:
- https://apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js
- javascripts/imagelink.js
- components/img_click.js
# hooks:
# - myhooks/my_hooks.py
markdown_extensions:
- abbr
- attr_list
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
    auto_title: true
    line_spans: __span
    linenums: true
    linenums_style: pymdownx-inline
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.snippets:
    base_path:
    - ./
    dedent_subsections: false
    url_download: true
- attr_list
- md_in_html
- pymdownx.superfences
- admonition
- pymdownx.details
- pymdownx.superfences
- toc:
    baselevel: 2
    permalink: '#'
    separator: _
- pymdownx.snippets:
    base_path:
    - ./
    dedent_subsections: false
    url_download: true
- pymdownx.arithmatex:
    generic: true
- footnotes
- def_list
- pymdownx.betterem
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.critic:
    mode: view
plugins:
- search
- tags:
    tags_file: tags.md
- blog:
    blog_dir: ./blog
    blog_toc: true
    post_date_format: full
- meta
- macros
repo_name: gitlab/mkdocs-material
repo_url: http://cl1157:30020/
site_name: "\u4E91\u7B14\u8BB0 my_mkdocs"
site_url: http://127.0.0.1
theme:
  features:
  - search.suggest
  - search.highlight
  - search.share
  - content.tooltips
  - content.tabs.link
  - content.code.copy
  - content.code.select
  - content.code.annotate
  - navigation.instant
  - navigation.instant.progress
  - navigation.tracking
  - navigation.tabs
  - navigation.footer
  - navigation.sections
  - navigation.path
  - navigation.prune
  - navigation.indexes
  - toc.follow
  - navigation.top
  - header.autohide
  - content.action.edit
  - content.action.view
  - announce.dismiss
  - navigation.instant.preview
  font:
    code: Roboto Mono
    text: Robotoimages/
  icon:
    admonition:
      abstract: octicons/checklist-16
      bug: octicons/bug-16
      danger: octicons/zap-16
      example: octicons/beaker-16
      failure: octicons/x-circle-16
      info: octicons/info-16
      note: octicons/tag-16
      question: octicons/question-16
      quote: octicons/quote-16
      success: octicons/check-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
    annotation: material/record-circle
    edit: material/pencil
    logo: material/library-shelves
    repo: fontawesome/brands/git-alt
    tag:
      css: fontawesome/brands/css3
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      mkdocs: fontawesome/brands/html5
    view: material/eye
  language: zh
  name: material
  palette:
  - accent: deep purple
    primary: green
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
validation:
  absolute_links: warn
  anchors: warn
  omitted_files: warn
  unrecognized_links: warn
watch:
- myhooks/conf_yamls/theme_palette.yml
- myhooks/conf_yamls/base.yml
- myhooks/conf_yamls/nav.yml
